version: '3.4'

services:
  todoclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  todoapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

networks:
  default:
    external:
      name: nat

